#pragma once

/* WiFi 配网页面 */
static const char WIFI_CONFIG_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\">"
"<title>Aidoll WiFi 配置</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f5f5f7;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:16px}"
".card{background:#fff;border-radius:20px;padding:28px 24px;width:100%;max-width:400px;box-shadow:0 2px 16px rgba(0,0,0,.08)}"
"h1{font-size:22px;font-weight:700;color:#1d1d1f;text-align:center;margin-bottom:4px}"
".sub{font-size:13px;color:#86868b;text-align:center;margin-bottom:24px}"
".input-group{margin-bottom:16px}"
"label{display:block;font-size:12px;font-weight:600;color:#6e6e73;margin-bottom:6px;letter-spacing:.3px}"
"input{width:100%;height:44px;border:1.5px solid #d2d2d7;border-radius:10px;padding:0 14px;font-size:15px;color:#1d1d1f;background:#fbfbfd;outline:none;transition:border-color .2s}"
"input:focus{border-color:#0071e3;background:#fff}"
".btn{width:100%;height:46px;border:none;border-radius:10px;font-size:16px;font-weight:600;cursor:pointer;transition:all .2s;color:#fff}"
".btn-primary{background:#0071e3;margin-bottom:8px}"
".btn-primary:hover{background:#0077ed}"
".btn-primary:disabled{background:#a1c9f5;cursor:not-allowed}"
".btn-scan{background:#34c759}"
".btn-scan:hover{background:#30b350}"
".list{list-style:none;margin-bottom:16px;max-height:200px;overflow-y:auto;border:1.5px solid #d2d2d7;border-radius:10px;display:none}"
".list.show{display:block}"
".list li{padding:12px 14px;border-bottom:1px solid #f0f0f5;cursor:pointer;display:flex;justify-content:space-between;align-items:center;font-size:14px;color:#1d1d1f}"
".list li:last-child{border-bottom:none}"
".list li:hover{background:#f5f5f7}"
".list li .signal{font-size:12px;color:#86868b}"
".list li .lock{margin-left:6px;font-size:11px}"
".status{text-align:center;font-size:13px;color:#86868b;margin-top:12px;min-height:20px}"
".status.error{color:#ff3b30}"
".status.ok{color:#34c759}"
".bind-box{background:#f0f4ff;border-radius:12px;padding:16px;text-align:center;margin-top:16px}"
".bind-label{font-size:11px;font-weight:600;color:#6e6e73;margin-bottom:6px;letter-spacing:.3px}"
".bind-code{font-size:28px;font-weight:800;color:#0071e3;letter-spacing:6px;font-family:monospace}"
".bind-hint{font-size:11px;color:#86868b;margin-top:6px}"
"</style>"
"</head>"
"<body>"
"<div class=\"card\">"
"<h1>明境 WiFi 配置</h1>"
"<p class=\"sub\">连接设备热点后访问此页面配置网络</p>"
"<div class=\"input-group\">"
"<button class=\"btn btn-scan\" onclick=\"scanNetworks()\" id=\"btnScan\">搜索WiFi网络</button>"
"<ul class=\"list\" id=\"netlist\"></ul>"
"</div>"
"<div class=\"input-group\">"
"<label>WiFi 名称 (SSID)</label>"
"<input type=\"text\" id=\"ssid\" placeholder=\"输入WiFi名称\">"
"</div>"
"<div class=\"input-group\">"
"<label>WiFi 密码</label>"
"<input type=\"password\" id=\"pwd\" placeholder=\"输入WiFi密码\">"
"</div>"
"<button class=\"btn btn-primary\" onclick=\"submitConfig()\" id=\"btnSubmit\">保存并连接</button>"
"<div class=\"status\" id=\"status\"></div>"
"<div class=\"bind-box\">"
"<div class=\"bind-label\">设备绑定码</div>"
"<div class=\"bind-code\" id=\"bindCode\">------</div>"
"<div class=\"bind-hint\">在管理平台输入此码完成设备绑定</div>"
"</div>"
"</div>"
"<script>"
"function setStatus(msg,cls){var s=document.getElementById('status');s.textContent=msg;s.className='status '+(cls||'')}"
"fetch('/bindcode').then(function(r){return r.json()}).then(function(d){document.getElementById('bindCode').textContent=d.code}).catch(function(){})"
"function scanNetworks(){"
"var btn=document.getElementById('btnScan');var list=document.getElementById('netlist');"
"btn.disabled=true;btn.textContent='搜索中...';list.classList.remove('show');list.innerHTML='';"
"setStatus('正在扫描WiFi网络...','');"
"fetch('/scan').then(function(r){return r.json()}).then(function(nets){"
"list.innerHTML='';"
"if(!nets||nets.length===0){setStatus('未发现WiFi网络','error');btn.disabled=false;btn.textContent='重新搜索';return}"
"nets.forEach(function(n){"
"var li=document.createElement('li');"
"var sig='',bars=0;"
"if(n.rssi>=-55)bars=4;else if(n.rssi>=-65)bars=3;else if(n.rssi>=-75)bars=2;else bars=1;"
"for(var i=0;i<4;i++)sig+=i<bars?'\\u25CF':'\\u25CB';"
"var lock=n.auth>0?' \\uD83D\\uDD12':'';"
"li.innerHTML='<span>'+n.ssid+'<span class=\"lock\">'+lock+'</span></span><span class=\"signal\">'+sig+'</span>';"
"li.onclick=function(){document.getElementById('ssid').value=n.ssid;list.classList.remove('show');if(n.auth>0)document.getElementById('pwd').focus()};"
"list.appendChild(li)"
"});"
"list.classList.add('show');setStatus('找到 '+nets.length+' 个网络，点击选择','ok')"
"}).catch(function(e){setStatus('搜索失败: '+e,'error')}).finally(function(){btn.disabled=false;btn.textContent='搜索WiFi网络'})"
"}"
"function submitConfig(){"
"var ssid=document.getElementById('ssid').value.trim();"
"var pwd=document.getElementById('pwd').value.trim();"
"if(!ssid){setStatus('请输入WiFi名称','error');return}"
"var btn=document.getElementById('btnSubmit');"
"btn.disabled=true;btn.textContent='保存中...';setStatus('正在保存配置...','');"
"fetch('/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ssid,password:pwd})})"
".then(function(r){return r.json()}).then(function(res){"
"if(res.status==='ok'){setStatus('配置成功！设备即将重启连接...','ok');btn.textContent='已保存'}else{setStatus('失败: '+(res.message||'未知错误'),'error');btn.disabled=false;btn.textContent='保存并连接'}"
"}).catch(function(e){setStatus('请求失败: '+e,'error');btn.disabled=false;btn.textContent='保存并连接'})"
"}"
"</script>"
"</body>"
"</html>";
