#!/usr/bin/env python3
"""Generate a 16x16 Chinese font header for SSD1306 OLED display.

Finds a Chinese TTF font on the system, renders each character as 16x16
1-bit bitmap, and writes firmware/main/zh_font.h.

Usage:
    python tools/gen_font.py
    python tools/gen_font.py --chars "你好世界"  # custom char list
    python tools/gen_font.py --font C:/Windows/Fonts/msyh.ttc  # specify font
"""

import argparse
import os
import struct
import sys

try:
    from PIL import Image, ImageFont, ImageDraw
except ImportError:
    print("ERROR: Pillow not found. Install it: pip install Pillow")
    sys.exit(1)

# ── Most common Chinese characters (top ~1500 by frequency) ──
# Covers ~95% of everyday Chinese text
COMMON_CHARS = (
    "的一是在不了有和人这中大为上个国我以要他时来用们生到作地于出就分对成会可主发年动"
    "同工也能下过子说产种面而方后多定行学法所民得经十三之进着等部度家电力里如水化高"
    "自二理起小物现实加量都两体制机当使点从业本去把性好应开它合还因由其些然前外天政"
    "四日那社义事平形相全表间样与关各重新线内数正心反你明看原又么利比或但质气第向道"
    "命此变条只没结解问意建月公无系军很情者最立代想已通并提直题党程展五果料象员革位"
    "入常文总次品式活设及管特件长求老头基资边流路级少图山统接知较将组见计别她手角期"
    "根论运农指几九区强放决西被干做必战先回则任取据处队南给色光门即保治北造百规热领"
    "七海口东导器压志世金增争济阶油思术极交受联什认六共权收证改清己美再采转更单风切"
    "打白教速花带安场身车例真务具万每目至达走积示议声报斗完类八离华名确才科张信马节"
    "话米整空元况今集温传土许步群广石记需段研界拉林律叫且究观越织装影算低持音众书布"
    "复容儿须际商非验连断深难近矿千周委素技备半办青省列习响约支般史感劳便团往酸历市"
    "克何除消构府称太准精值号率族维划选标写存候毛亲快效斯院查江型眼王按格养易置派层"
    "片始却专状育厂京识适属圆包火住调满县局照参红细引听该铁价严首底液官德随病苏失尔"
    "死讲配女黄推显谈罪神艺呢席含企望密批营项防举球英氧势告李台落木帮轮破亚师围注远"
    "字材排供河态封另施减树溶怎止案言士均武固叶鱼波视仅费紧爱左章早朝害续轻服试食充"
    "兵源判护司足某练差致板田降黑犯负击范继兴似余坚曲输修故城夫够送笔船占右财吃富春"
    "职觉汉画功巴跟虽杂飞检吸助升阳互初创抗考投坏策古径换未跑留钢曾端责站简述钱副尽"
    "帝射草冲承独令限阿宣环双请超微让控州良轴找否纪益依优顶础载倒房突坐粉敌略客袁冷"
    "胜绝析块剂测丝协重诉念陈仍罗盐友洋错苦夜刑移频逐靠混母短皮终聚汽村云哪既距卫停"
    "烈央察烧行境若印洲刻括激孔搞甚室待核校散侵吧甲游久菜味旧模湖货损预阻毫普稳乙妈"
    "植息扩银语挥酒守拿序纸医缺雨吗针刘啊急唱误训愿审附获茶鲜粮斤孩脱硫肥善龙演父渐"
    "血欢械掌歌沙著刚攻谓盾讨晚粒乱燃矛乎杀药宁鲁贵钟煤读班伯香介迫句丰培握兰担弦蛋"
    "沉假穿执答乐谁顺烟缩征脸喜松脚困异免背星福买染井概慢怕磁倍祖皇促静补评翻肉践尼"
    "衣宽扬棉希伤操垂秋宜氢套笔督振架亮末宪庆编牛触映雷销诗座居抓裂胞呼娘景威绿晶厚"
    "盟衡鸡孙延危胶屋乡临陆顾掉呀灯岁措束耐剧玉赵跳哥季课凯胡额款绍卷齐伟蒸殖勇苗川"
    "炉岩弱零杨奏沿露杆探滑镇饭浓航怀赶库夺伊灵税了途灭赛归召鼓播盘裁险康唯录菌纯借"
    "糖盖符私努堂域枪润幅哈竟熟虫泽脑壤碳欧遍侧寨敢彻虑斜薄庭都纳弹饲伸折麦湿暗荷瓦"
    "塞床筑恶户访塔奇透梁刀旋迹卡氯遇份毒泥退洗摆灰彩卖耗夏择忙铜献硬予繁圈雪函亦抽"
    "篇阵阴丁尺追堆雄迎泛爸爸楼怕辟印松脚困异免背星"
)

# ── Try to find a Chinese font on the system ──
FONT_CANDIDATES = [
    # Windows
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/msyhbd.ttc",
    "C:/Windows/Fonts/simhei.ttf",
    "C:/Windows/Fonts/simsun.ttc",
    "C:/Windows/Fonts/Deng.ttf",
    "C:/Windows/Fonts/Dengb.ttf",
    # Linux / WSL
    "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc",
    "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf",
    # macOS
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/Library/Fonts/Arial Unicode.ttf",
]


def find_chinese_font():
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            return path
    return None


def render_char(font, ch):
    """Render a single character as 16x16 1-bit bitmap.
    Returns 32 bytes (row-major, MSB first)."""
    img = Image.new("L", (16, 16), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, -2), ch, font=font, fill=255)  # -2 y-offset for better centering
    data = bytearray(32)
    for y in range(16):
        byte_val = 0
        for x in range(16):
            if img.getpixel((x, y)) > 127:
                byte_val |= 1 << (7 - (x % 8))
            if x % 8 == 7:
                data[y * 2 + x // 8] = byte_val
                byte_val = 0
    return bytes(data)


def generate(chars, font_path, output_path):
    print(f"Using font: {font_path}")
    font = ImageFont.truetype(font_path, 14)

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for ch in chars:
        if ch not in seen:
            seen.add(ch)
            unique.append(ch)

    # Add ASCII fallback
    for i in range(0x20, 0x7F):
        unique.append(chr(i))

    # Render each character
    glyphs = []
    for ch in unique:
        try:
            bmp = render_char(font, ch)
            cp = ord(ch)
            glyphs.append((cp, bmp))
        except Exception as e:
            print(f"  skip U+{ord(ch):04X} ({ch}): {e}")

    print(f"Generated {len(glyphs)} glyphs")

    # Sort by codepoint for binary search in C code
    glyphs.sort(key=lambda g: g[0])

    # Write C header
    count = len(glyphs)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/gen_font.py — DO NOT EDIT\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define ZH_FONT_COUNT {count}\n\n")

        # Glyph data array: 4 bytes per glyph (2-byte codepoint + 2-byte offset)
        # Followed by bitmap data
        f.write("typedef struct { uint16_t codepoint; uint16_t offset; } zh_glyph_index_t;\n\n")

        # Build bitmap data
        bitmap_data = bytearray()
        index_entries = []
        offset = 0
        for cp, bmp in glyphs:
            index_entries.append((cp, offset))
            bitmap_data.extend(bmp)
            offset += 32

        # Write index
        f.write("static const zh_glyph_index_t zh_font_index[ZH_FONT_COUNT] = {\n")
        for cp, off in index_entries:
            f.write(f"    {{0x{cp:04X}, {off}}},  // U+{cp:04X}\n")
        f.write("};\n\n")

        # Write bitmap data
        f.write(f"static const uint8_t zh_font_bitmap[{len(bitmap_data)}] = {{\n")
        for i in range(0, len(bitmap_data), 16):
            chunk = bitmap_data[i:i + 16]
            hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
            f.write(f"    {hex_str},\n")
        f.write("};\n")

    print(f"Wrote {output_path} ({count} glyphs, {len(bitmap_data)} bytes bitmap)")


def main():
    parser = argparse.ArgumentParser(description="Generate Chinese font header for OLED")
    parser.add_argument("--font", help="Path to TTF/OTC font file")
    parser.add_argument("--chars", help="Extra characters to include")
    parser.add_argument("--output", default=None, help="Output path")
    args = parser.parse_args()

    font_path = args.font or find_chinese_font()
    if not font_path:
        print("ERROR: No Chinese font found. Install one or use --font")
        print("  Ubuntu/Debian: sudo apt install fonts-wqy-zenhei")
        print("  Or download: https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf")
        sys.exit(1)

    chars = COMMON_CHARS
    if args.chars:
        chars += args.chars

    script_dir = os.path.dirname(os.path.abspath(__file__))
    output = args.output or os.path.join(script_dir, "..", "main", "zh_font.h")
    generate(chars, font_path, output)


if __name__ == "__main__":
    main()
